### ISSUE TITLE
Specific Characters not usable at all

### ISSUE THREAD

**Issue by f0ru0l0rd** [Dragooon/smf-mentions#7]
Hello,

My clan is wanting to install this plugin, unfortunately, our clan members have a tag in front of their name (eg }CoG{, [HOA]). When typing @ followed by any of those symbols, a match is not made, nor is the remainder of the name. As an example, }CoG{Simon will not pull up, even if I just used Simon. They do not exist on the list in any way/shape/form. All other names show up just fine.

I tried a few hacks to see what I could come up with, but I don't know enough about SMF to make sure it's pulling the names from the DB to begin with (though I imagine that it is not).

Thank you!
David

**Comment by Al-eXs** [comment]
Do you use the MOD package that is in the SMF site or you downloaded the zip from here?

Te code here has some bugfixes that the author didn't update yet in the SMF site package, and that kind of characters work with one of that fixes.

**Comment by f0ru0l0rd** [comment]
My apologies, this issue has been fixed with the newest update. Thank you for the information @Al-eXs, and thank you @Dragooon for making such an awesome piece of code!
